"""
Markdown export for analysis reports.
"""
from datetime import datetime
from typing import Dict, Any


def export_markdown(report: Dict[str, Any]) -> str:
    """
    Export analysis report as Markdown.
    
    Args:
        report: Analysis report dictionary
        
    Returns:
        Markdown string
    """
    md_lines = []
    
    # Header
    md_lines.append(f"# CodeAtlas Analysis Report\n")
    md_lines.append(f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n")
    
    # Basic info
    md_lines.append(f"## 📋 Repository Information\n")
    md_lines.append(f"- **Path**: `{report.get('path', 'Unknown')}`")
    md_lines.append(f"- **Analysis ID**: `{report.get('analysis_id', 'N/A')}`")
    md_lines.append(f"- **Status**: {report.get('status', 'unknown')}\n")
    
    # Summary section
    summary = report.get('summary', {})
    if summary:
        md_lines.append(f"## 📊 Summary\n")
        md_lines.append(f"- **Total Files**: {summary.get('total_files', 0)}")
        md_lines.append(f"- **Files Analyzed**: {summary.get('files_analyzed', 0)}")
    
    # Metrics section
    metrics = report.get('metrics', {})
    if metrics and 'error' not in metrics:
        md_lines.append(f"\n## 📈 Metrics\n")
        md_lines.append(f"- **File Count**: {metrics.get('file_count', 0)}")
        md_lines.append(f"- **Total Lines**: {metrics.get('total_lines', 'N/A')}")
        md_lines.append(f"- **Total Size**: {metrics.get('total_size_kb', 'N/A')} KB")
        md_lines.append(f"- **Risk Level**: **{metrics.get('risk', 'N/A').upper()}**")
        md_lines.append(f"- **Risk Score**: {metrics.get('risk_score', 0)}/100")
        
        # File types
        file_types = metrics.get('file_types', {})
        if file_types:
            md_lines.append(f"\n### File Types\n")
            for file_type, count in sorted(file_types.items(), key=lambda x: x[1], reverse=True):
                md_lines.append(f"- {file_type.title()}: {count}")
        
        # Languages
        languages = metrics.get('languages', [])
        if languages:
            md_lines.append(f"\n### Languages\n")
            md_lines.append(f"- {', '.join(languages)}")
    
    # Security section
    security = report.get('security', {})
    if security and 'error' not in security:
        md_lines.append(f"\n## 🔒 Security\n")
        md_lines.append(f"- **Secrets Found**: {security.get('secrets_found', 0)}")
        md_lines.append(f"- **Vulnerabilities Found**: {security.get('vulnerabilities_found', 0)}")
        md_lines.append(f"- **Overall Risk**: {security.get('risk_level', 'N/A').upper()}")
    
    # Architecture section
    architecture = report.get('architecture', {})
    if architecture and 'error' not in architecture:
        layers = architecture.get('layers', {})
        if layers:
            md_lines.append(f"\n## 🏗️ Architecture\n")
            for layer, files in layers.items():
                if files:
                    md_lines.append(f"\n### {layer.upper()} Layer\n")
                    md_lines.append(f"- **Files**: {len(files)}")
                    for file in files[:3]:
                        md_lines.append(f"  - `{file}`")
                    if len(files) > 3:
                        md_lines.append(f"  - *... and {len(files) - 3} more*")
    
    # Python analysis
    python_analysis = report.get('python_analysis', {})
    if python_analysis and 'error' not in python_analysis:
        md_lines.append(f"\n## 🐍 Python Analysis\n")
        md_lines.append(f"- **Python Files**: {python_analysis.get('python_files_count', 0)}")
        md_lines.append(f"- **Functions**: {python_analysis.get('total_functions', 0)}")
        md_lines.append(f"- **Classes**: {python_analysis.get('total_classes', 0)}")
        md_lines.append(f"- **Avg Complexity**: {python_analysis.get('avg_complexity_score', 0)}")
    
    # Footer
    md_lines.append(f"\n---\n")
    md_lines.append(f"*Generated by [CodeAtlas](http://localhost:8000/) - AI-Powered Code Intelligence Platform*")
    
    return '\n'.join(md_lines)