"""
PDF export for analysis reports.
"""
import io
from typing import Dict, Any, Optional
from datetime import datetime

# Try to import reportlab, but don't fail if not installed
try:
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
    from reportlab.lib import colors
    PDF_AVAILABLE = True
except ImportError:
    PDF_AVAILABLE = False


def export_pdf(report: Dict[str, Any]) -> Optional[bytes]:
    """
    Export analysis report as PDF.
    
    Args:
        report: Analysis report dictionary
        
    Returns:
        PDF bytes or None if PDF generation fails
    """
    if not PDF_AVAILABLE:
        print("⚠️  PDF export requires reportlab. Install with: pip install reportlab")
        return None
    
    try:
        # Create PDF in memory
        buffer = io.BytesIO()
        
        # Setup document
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )
        
        # Build story (content)
        story = _build_pdf_content(report)
        
        # Generate PDF
        doc.build(story)
        
        # Get PDF bytes
        pdf_bytes = buffer.getvalue()
        buffer.close()
        
        return pdf_bytes
        
    except Exception as e:
        print(f"❌ PDF generation failed: {str(e)}")
        return None


def _build_pdf_content(report: Dict[str, Any]) -> list:
    """Build PDF content elements."""
    if not PDF_AVAILABLE:
        return []
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    styles.add(ParagraphStyle(
        name='Title',
        parent=styles['Heading1'],
        fontSize=24,
        spaceAfter=30,
        textColor=colors.HexColor('#2d3748')
    ))
    
    styles.add(ParagraphStyle(
        name='Subtitle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#718096')
    ))
    
    styles.add(ParagraphStyle(
        name='CardTitle',
        parent=styles['Heading2'],
        fontSize=16,
        spaceAfter=12,
        textColor=colors.HexColor('#2d3748')
    ))
    
    story = []
    
    # Header
    story.append(Paragraph("CodeAtlas Analysis Report", styles['Title']))
    story.append(Spacer(1, 12))
    
    # Subtitle
    subtitle_text = f"""
    <b>Repository:</b> {report.get('path', 'Unknown')}<br/>
    <b>Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}<br/>
    <b>Analysis ID:</b> {report.get('analysis_id', 'N/A')}
    """
    story.append(Paragraph(subtitle_text, styles['Subtitle']))
    story.append(Spacer(1, 40))
    
    # Summary Section
    story.append(Paragraph("📊 Summary", styles['CardTitle']))
    story.append(Spacer(1, 20))
    
    # Add summary table
    summary_data = _create_summary_table(report)
    if summary_data:
        summary_table = Table(summary_data, colWidths=[2*inch, 2*inch])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f7fafc')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#2d3748')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#e2e8f0')),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        story.append(summary_table)
        story.append(Spacer(1, 40))
    
    # Page break if needed
    story.append(PageBreak())
    
    # Footer
    story.append(Spacer(1, 60))
    footer_text = """
    <para alignment="center">
    <font size="9" color="#718096">
    Generated by <b>CodeAtlas</b> • AI-Powered Code Intelligence Platform<br/>
    For more information, visit: http://localhost:8000/docs
    </font>
    </para>
    """
    story.append(Paragraph(footer_text, styles['Normal']))
    
    return story


def _create_summary_table(report: Dict[str, Any]) -> list:
    """Create summary table data."""
    summary = report.get('summary', {})
    metrics = report.get('metrics', {})
    
    if not metrics or 'error' in metrics:
        return []
    
    data = [
        ['Metric', 'Value'],
        ['Total Files', str(summary.get('total_files', 'N/A'))],
        ['Total Lines', str(metrics.get('total_lines', 'N/A'))],
        ['Total Size', f"{metrics.get('total_size_kb', 'N/A')} KB"],
        ['Risk Level', metrics.get('risk', 'N/A').upper()],
        ['Risk Score', f"{metrics.get('risk_score', 'N/A')}/100"],
    ]
    
    # Add languages
    languages = metrics.get('languages', [])
    if languages:
        data.append(['Languages', ', '.join(languages)])
    
    return data


def export_pdf_to_file(report: Dict[str, Any], filename: str) -> bool:
    """
    Export analysis report as PDF file.
    
    Args:
        report: Analysis report dictionary
        filename: Output filename
        
    Returns:
        True if successful, False otherwise
    """
    pdf_bytes = export_pdf(report)
    
    if not pdf_bytes:
        return False
    
    try:
        with open(filename, 'wb') as f:
            f.write(pdf_bytes)
        return True
    except Exception as e:
        print(f"❌ Failed to write PDF file: {str(e)}")
        return False