"""
README generator for analyzed projects.
"""
from datetime import datetime
from typing import Dict, Any
import textwrap


def generate_readme(analysis: Dict[str, Any]) -> str:
    """
    Generate comprehensive README from analysis.
    
    Args:
        analysis: Analysis results dictionary
        
    Returns:
        README markdown string
    """
    if not analysis:
        return "# Project Analysis\n\nNo analysis data available."
    
    # Extract data with defaults
    summary = analysis.get('summary', {})
    metrics = analysis.get('metrics', {})
    architecture = analysis.get('architecture', {})
    security = analysis.get('security', {})
    python_analysis = analysis.get('python_analysis', {})
    
    # Prepare sections
    sections = []
    
    # Header
    repo_path = analysis.get('path', 'Unknown')
    repo_name = repo_path.split('/')[-1] if '/' in repo_path else repo_path
    
    sections.append(f"""# {repo_name}

*Generated by CodeAtlas on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*

## 📋 Overview

- **Repository**: `{repo_path}`
- **Analysis ID**: `{analysis.get('analysis_id', 'N/A')}`
- **Status**: {analysis.get('status', 'N/A')}
- **Files Analyzed**: {summary.get('total_files', 0)}
""")
    
    # Metrics section
    if metrics and 'error' not in metrics:
        sections.append(f"""
## 📊 Metrics

- **Total Files**: {metrics.get('file_count', 0)}
- **Total Lines**: {metrics.get('total_lines', 'N/A')}
- **Total Size**: {metrics.get('total_size_kb', 'N/A')} KB
- **Average File Size**: {metrics.get('avg_file_size_kb', 'N/A')} KB
- **Risk Level**: **{metrics.get('risk', 'N/A').upper()}** (Score: {metrics.get('risk_score', 0)}/100)
""")
        
        # File types
        file_types = metrics.get('file_types', {})
        if file_types:
            sections.append("\n### File Types\n")
            for file_type, count in sorted(file_types.items(), key=lambda x: x[1], reverse=True):
                sections.append(f"- {file_type.title()}: {count} files")
        
        # Languages
        languages = metrics.get('languages', [])
        if languages:
            sections.append(f"\n### Languages\n")
            sections.append(f"- {', '.join(languages)}")
    
    # Architecture section
    if architecture and 'error' not in architecture:
        layers = architecture.get('layers', {})
        if layers:
            sections.append("""
## 🏗️ Architecture

The project follows a layered architecture:
""")
            for layer, files in layers.items():
                if files:  # Only show non-empty layers
                    sections.append(f"\n### {layer.upper()} Layer ({len(files)} files)")
                    # Show top 5 files per layer
                    for file in files[:5]:
                        sections.append(f"- `{file}`")
                    if len(files) > 5:
                        sections.append(f"- *... and {len(files) - 5} more*")
    
    # Security section
    if security and 'error' not in security:
        secrets_found = security.get('secrets_found', 0)
        vulns_found = security.get('vulnerabilities_found', 0)
        
        sections.append(f"""
## 🔒 Security

### Summary
- **Secrets Found**: {secrets_found}
- **Vulnerabilities Found**: {vulns_found}
- **Overall Risk**: {security.get('risk_level', 'N/A').upper() if isinstance(security, dict) else 'N/A'}
""")
        
        # Show secrets if found
        if secrets_found > 0:
            sections.append("\n### Potential Secrets Found\n")
            secrets = security.get('secrets', [])
            for i, secret in enumerate(secrets[:3], 1):
                if isinstance(secret, dict):
                    sections.append(f"{i}. **{secret.get('type', 'Secret')}** in `{secret.get('file', 'Unknown')}`")
                    sections.append(f"   - Line: {secret.get('line', 'N/A')}")
                    sections.append(f"   - Risk: {secret.get('risk_level', 'N/A')}")
                else:
                    sections.append(f"{i}. {secret}")
            
            if secrets_found > 3:
                sections.append(f"\n*... and {secrets_found - 3} more secrets*")
        
        # Show vulnerabilities if found
        if vulns_found > 0:
            sections.append("\n### Potential Vulnerabilities\n")
            vulns = security.get('vulnerabilities', [])
            for i, vuln in enumerate(vulns[:3], 1):
                if isinstance(vuln, dict):
                    sections.append(f"{i}. **{vuln.get('pattern', 'Vulnerability')}** in `{vuln.get('file', 'Unknown')}`")
                    sections.append(f"   - Line: {vuln.get('line', 'N/A')}")
                    sections.append(f"   - Severity: {vuln.get('severity', 'N/A')}")
                else:
                    sections.append(f"{i}. {vuln}")
            
            if vulns_found > 3:
                sections.append(f"\n*... and {vulns_found - 3} more vulnerabilities*")
    
    # Python analysis section
    if python_analysis and 'error' not in python_analysis:
        sections.append(f"""
## 🐍 Python Analysis

- **Python Files**: {python_analysis.get('python_files_count', 0)}
- **Functions Found**: {python_analysis.get('total_functions', 'N/A')}
- **Classes Found**: {python_analysis.get('total_classes', 'N/A')}
- **Average Complexity**: {python_analysis.get('avg_complexity_score', 'N/A')}
""")
        
        # Show most complex files
        complex_files = python_analysis.get('most_complex_files', [])
        if complex_files:
            sections.append("\n### Most Complex Files\n")
            for file_data in complex_files[:3]:
                sections.append(f"- `{file_data.get('file', 'Unknown')}`")
                sections.append(f"  - Complexity: {file_data.get('complexity_score', 'N/A')}")
                sections.append(f"  - Functions: {file_data.get('functions', 'N/A')}")
                sections.append(f"  - Classes: {file_data.get('classes', 'N/A')}")
    
    # Recommendations section
    risk_level = metrics.get('risk', 'low')
    recommendations = _generate_recommendations(analysis)
    
    if recommendations:
        sections.append(f"""
## 💡 Recommendations

Based on the analysis ({risk_level.upper()} risk level):
""")
        for rec in recommendations:
            sections.append(f"- {rec}")
    
    # Footer
    sections.append("""
---

### About This Report

This README was automatically generated by **CodeAtlas**, an AI-powered code intelligence platform.

**What this report provides:**
- Codebase metrics and statistics
- Architecture understanding
- Security vulnerability detection
- Maintenance recommendations

**Next steps:**
1. Review security findings
2. Address high-risk issues
3. Consider refactoring complex files
4. Update documentation

*For more detailed analysis, export the full report in JSON format.*
""")
    
    return '\n'.join(sections)


def _generate_recommendations(analysis: Dict[str, Any]) -> list:
    """Generate recommendations based on analysis."""
    recommendations = []
    metrics = analysis.get('metrics', {})
    security = analysis.get('security', {})
    
    # File count recommendations
    file_count = metrics.get('file_count', 0)
    if file_count > 1000:
        recommendations.append("Consider splitting this large codebase into smaller, focused modules.")
    elif file_count > 500:
        recommendations.append("The codebase is moderately large. Ensure proper module separation.")
    
    # Risk level recommendations
    risk_level = metrics.get('risk', 'low')
    if risk_level in ['high', 'critical']:
        recommendations.append("Address high-risk issues immediately, starting with security vulnerabilities.")
    elif risk_level == 'medium':
        recommendations.append("Review medium-risk findings and plan refactoring.")
    
    # Security recommendations
    if security and 'error' not in security:
        secrets_found = security.get('secrets_found', 0)
        vulns_found = security.get('vulnerabilities_found', 0)
        
        if secrets_found > 0:
            recommendations.append(f"Remove {secrets_found} hardcoded secret(s) and use environment variables.")
        
        if vulns_found > 0:
            recommendations.append(f"Review {vulns_found} potential vulnerability(ies) for security fixes.")
    
    # Architecture recommendations
    architecture = analysis.get('architecture', {})
    if architecture and 'error' not in architecture:
        layers = architecture.get('layers', {})
        other_files = len(layers.get('other', []))
        
        if other_files > 20:
            recommendations.append(f"Organize {other_files} uncategorized files into proper architectural layers.")
    
    # Python-specific recommendations
    python_analysis = analysis.get('python_analysis', {})
    if python_analysis and 'error' not in python_analysis:
        avg_complexity = python_analysis.get('avg_complexity_score', 0)
        if avg_complexity > 50:
            recommendations.append("Reduce function/class complexity through refactoring.")
    
    # Add general best practices
    recommendations.extend([
        "Ensure all secrets are stored in environment variables or secret managers.",
        "Add comprehensive tests for critical functionality.",
        "Document public APIs and complex business logic.",
        "Consider adding type hints for better code clarity.",
        "Setup CI/CD pipeline for automated testing and deployment.",
    ])
    
    return recommendations[:10]  # Limit to top 10 recommendations


def generate_minimal_readme(analysis: Dict[str, Any]) -> str:
    """
    Generate minimal README for quick overview.
    
    Args:
        analysis: Analysis results
        
    Returns:
        Minimal README markdown
    """
    summary = analysis.get('summary', {})
    metrics = analysis.get('metrics', {})
    
    return f"""# Project Snapshot

## Quick Stats
- **Files**: {summary.get('total_files', 0)}
- **Risk**: {metrics.get('risk', 'N/A').upper()}
- **Languages**: {', '.join(metrics.get('languages', ['N/A']))}

## Key Findings
{_get_key_findings(analysis)}

*Generated by CodeAtlas*
"""


def _get_key_findings(analysis: Dict[str, Any]) -> str:
    """Extract key findings from analysis."""
    findings = []
    
    # Security findings
    security = analysis.get('security', {})
    if security and 'error' not in security:
        secrets = security.get('secrets_found', 0)
        vulns = security.get('vulnerabilities_found', 0)
        
        if secrets > 0:
            findings.append(f"- 🔒 {secrets} potential secret(s) found")
        if vulns > 0:
            findings.append(f"- ⚠️ {vulns} potential vulnerability(ies) found")
    
    # Complexity findings
    metrics = analysis.get('metrics', {})
    if metrics and 'error' not in metrics:
        large_files = metrics.get('large_files_count', 0)
        if large_files > 0:
            findings.append(f"- 📈 {large_files} large file(s) (may need refactoring)")
    
    # Architecture findings
    architecture = analysis.get('architecture', {})
    if architecture and 'error' not in architecture:
        layers = architecture.get('layers', {})
        if layers.get('other'):
            findings.append(f"- 🏗️ {len(layers['other'])} file(s) not following clear architecture")
    
    if not findings:
        findings.append("- ✅ Codebase looks well-structured")
    
    return '\n'.join(findings)